#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: v1
kind: Secret
metadata:
  name: org1-tls-cert-issuer-secret
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNLRENDQWM2Z0F3SUJBZ0lVZUZhVWpkQzNXUnlNdHU0TExaM2hlQmIyVG5Jd0NnWUlLb1pJemowRUF3SXcKYURFTE1Ba0dBMVVFQmhNQ1ZWTXhGekFWQmdOVkJBZ1REazV2Y25Sb0lFTmhjbTlzYVc1aE1SUXdFZ1lEVlFRSwpFd3RJZVhCbGNteGxaR2RsY2pFUE1BMEdBMVVFQ3hNR1JtRmljbWxqTVJrd0Z3WURWUVFERXhCbVlXSnlhV010ClkyRXRjMlZ5ZG1WeU1CNFhEVEl5TURFeE9ERTRNRGt3TUZvWERUTTNNREV4TkRFNE1Ea3dNRm93YURFTE1Ba0cKQTFVRUJoTUNWVk14RnpBVkJnTlZCQWdURGs1dmNuUm9JRU5oY205c2FXNWhNUlF3RWdZRFZRUUtFd3RJZVhCbApjbXhsWkdkbGNqRVBNQTBHQTFVRUN4TUdSbUZpY21sak1Sa3dGd1lEVlFRREV4Qm1ZV0p5YVdNdFkyRXRjMlZ5CmRtVnlNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVLdHBid0RMNStwcWV1bUNxUlAxN0ltT1gKSytxclViMTAyTU9XeE1iaDBKbExHdm1DS05DeFhjNnFNSnMvSE1uakJyaWZ2VlZUdW4xbzB4U2FGVU5wVHFOVwpNRlF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQklHQTFVZEV3RUIvd1FJTUFZQkFmOENBUUV3SFFZRFZSME9CQllFCkZMUU4zVk1zRkU4SEMrZUZJZ2E5VkNTZUpqNVdNQThHQTFVZEVRUUlNQWFIQkg4QUFBRXdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQU8vNGttZm5MWml2c05BZ1hRQzFYUHQrS2NyOGJGUGlRbmhzNWo5SUNJdFVBaUIrei9uZgpjdURvcjRqUFdMSjNVL1NZYnVkK1g4NEt1UzFseVNTME9Pbmpndz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZzFhdXpCUk9nT1dxc3FwL1UKYlp3M2dtSk5sZlhOS3FMc2NCWUZzdmdhdWZLaFJBTkNBQVFxMmx2QU12bjZtcDY2WUtwRS9Yc2lZNWNyNnF0Ugp2WFRZdzViRXh1SFFtVXNhK1lJbzBMRmR6cW93bXo4Y3llTUd1Sis5VlZPNmZXalRGSm9WUTJsTwotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t
