#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: v1
kind: Secret
metadata:
  name: org2-tls-cert-issuer-secret
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNKekNDQWM2Z0F3SUJBZ0lVTVdkYlZ1RGFJU1BIQnQrVE1ENlNkN21URmowd0NnWUlLb1pJemowRUF3SXcKYURFTE1Ba0dBMVVFQmhNQ1ZWTXhGekFWQmdOVkJBZ1REazV2Y25Sb0lFTmhjbTlzYVc1aE1SUXdFZ1lEVlFRSwpFd3RJZVhCbGNteGxaR2RsY2pFUE1BMEdBMVVFQ3hNR1JtRmljbWxqTVJrd0Z3WURWUVFERXhCbVlXSnlhV010ClkyRXRjMlZ5ZG1WeU1CNFhEVEl5TURFeE9ERTRNRGt3TUZvWERUTTNNREV4TkRFNE1Ea3dNRm93YURFTE1Ba0cKQTFVRUJoTUNWVk14RnpBVkJnTlZCQWdURGs1dmNuUm9JRU5oY205c2FXNWhNUlF3RWdZRFZRUUtFd3RJZVhCbApjbXhsWkdkbGNqRVBNQTBHQTFVRUN4TUdSbUZpY21sak1Sa3dGd1lEVlFRREV4Qm1ZV0p5YVdNdFkyRXRjMlZ5CmRtVnlNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVWWWNvQ2p4VXFFS1RaVThxOHJBd0c3RVMKa0Z4V3lmSjVyZGhHRktESWI1R1ZkR0lQc0NtSU03bS9TTFRQMGlCWkdTb2IwRUVJZENKMzZQWW9ldVY3NDZOVwpNRlF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQklHQTFVZEV3RUIvd1FJTUFZQkFmOENBUUV3SFFZRFZSME9CQllFCkZHUlc5elBYa3V3cVdyYnBscVdYUTc5Zm5wdlVNQThHQTFVZEVRUUlNQWFIQkg4QUFBRXdDZ1lJS29aSXpqMEUKQXdJRFJ3QXdSQUlnQ1FJM3ZwVjYrN0JCL0czem9xeHNVeUtwN2ZUMlFIVTczeExBSjNMN0RXZ0NJRTB4L0xuTgpkN0U0a1BWVFFjN05hdGtSUWlzNUQ3L0djaXc4TGozaXJDL2YKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoK
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ0pnWlhOajREOWpKcVVlbzgKT3JoS2ZNVWNrenE5RTM4M29jSW15aDhPQlNHaFJBTkNBQVJWaHlnS1BGU29RcE5sVHlyeXNEQWJzUktRWEZiSgo4bm10MkVZVW9NaHZrWlYwWWcrd0tZZ3p1YjlJdE0vU0lGa1pLaHZRUVFoMEluZm85aWg2NVh2agotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
