#
# SPDX-License-Identifier: Apache-2.0
#

trigger:
  - main
  - release-1.4
  - release-2.2

variables:
  FABRIC_VERSION: 2.4
  GO_BIN: $(Build.Repository.LocalPath)/bin
  GO_VER: 1.16.7
  NODE_VER: 16.x
  PATH: $(Build.Repository.LocalPath)/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin

jobs:

  - job: KubeTestNetworkBasic
    displayName: Kube Test Network Basic
    pool:
      vmImage: ubuntu-20.04
    strategy:
      matrix:
        Docker-Typescript:
          CONTAINER_CLI: docker
          CLIENT_LANGUAGE: typescript
#        Podman-Typescript:
#          CONTAINER_CLI: podman
#          CLIENT_LANGUAGE: typescript
#        Nerdctl-Typescript:
#          CONTAINER_CLI: nerdctl
#          CLIENT_LANGUAGE: typescript
    steps:
      - template: templates/install-k8s-deps.yml
      - script: ../ci/scripts/run-k8s-test-network-basic.sh
        workingDirectory: test-network-k8s
        displayName: Run Kubernetes Test Network Basic Asset Transfer
