#
# SPDX-License-Identifier: Apache-2.0
#

trigger:
  - main
  - release-1.4
  - release-2.2

variables:
  - name: FABRIC_VERSION
    value: 2.4
  - name: GOPATH
    value: $(Build.Repository.LocalPath)
  - name: GO_BIN
    value: $(GOPATH)/bin
  - name: GO_VER
    value: 1.18.3
  - name: NODE_VER
    value: 16.x
  - name: PATH
    value: $(GOPATH)/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
  - group: credentials

jobs:
  - job: REST_Sample
    displayName: REST Server Sample
    pool:
      vmImage: ubuntu-20.04
    steps:
      - template: templates/asset-transfer-basic/azure-pipelines-rest.yml
