name: Test Network Gateway
run-name: ${{ github.actor }} is running the test-network gateway tests

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test-network-gateway:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        chaincode-language:
          - go
          - javascript
          - typescript
          - java

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: checkout
        uses: actions/checkout@v3

      - name: Install fabric CLI
        run: |
          curl -sSL https://raw.githubusercontent.com/hyperledger/fabric/main/scripts/install-fabric.sh | bash -s -- binary
          echo ${PWD}/bin >> $GITHUB_PATH

      - name: Install retry CLI
        run: curl -sSL https://raw.githubusercontent.com/kadwanev/retry/master/retry -o ./bin/retry && chmod +x ./bin/retry

      - name: Pull Fabric Docker Images
        run: ./ci/scripts/pullFabricImages.sh

      - name: Run Test Network Off Chain
        working-directory: test-network
        env:
          CHAINCODE_LANGUAGE: ${{ matrix.chaincode-language }}
        run: ../ci/scripts/run-test-network-gateway.sh

